SDProject/SDProject/Models/Quiz.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Web;

namespace OLS.Models
{
    public class Quiz
    {
        [Required]
        public int quiz_id { set; get; }
        [Required]
        public int admin_id { set; get; }
        [Required]
        public int topic_id { set; get; }
        public string topic_name { set; get; }
        [Required]
        public string title { set; get; }
        [Required]
        public DateTime created_on { set; get; }
        //[Required]
        //public int duration { set; get; }
        //public string duration_string { set; get; }
        public bool participated { set; get; }
        public int obtained_mark { set; get; }
        public string created_by { set; get; }

        [Required]
        public List<Q_A> q_As { set; get; }


        //----------------------------------------------------------------------------------------------------------------------------------------------------------------


        public bool SetQuizDB(Quiz quiz)    // inserts the data of a quiz submitted via form in the view
        {
            string connString = ConfigurationManager.ConnectionStrings["DBConnString"].ConnectionString;
            object generatedId = null;

            SqlConnection sqlConnection = new SqlConnection(connString);

            using (sqlConnection)
            {
                SqlCommand sqlCommand = new SqlCommand();
                sqlCommand.CommandText = "INSERT INTO [quiz] OUTPUT inserted.quiz_id VALUES (@admin_id, @topic_id, @title, @created_on)"; // SQL identifies a parameter by the '@' at the beginning
                sqlCommand.Connection = sqlConnection;

                sqlCommand.Parameters.AddWithValue("@admin_id", quiz.admin_id);             // defining the "parameter" used in the sql query
                                                                                            // setting the value for that parameter (i.e finding "@admin_id" parameter and replacing it the desired value)
                sqlCommand.Parameters.AddWithValue("@topic_id", quiz.topic_id);
                sqlCommand.Parameters.AddWithValue("@title", quiz.title);
                sqlCommand.Parameters.AddWithValue("@created_on", DateTime.Now);
                // sqlCommand.Parameters.AddWithValue("@duration", quiz.duration);

                sqlConnection.Open();
                generatedId = sqlCommand.ExecuteScalar();
                sqlConnection.Close();
            }

            if (generatedId != null)    // done with storing a quiz entry in the quiz table, now onto storing the questions
            {
                // int quiz_id_qatbl = Convert.ToInt32(generatedId);

                for (int i = 0; i < q_As.Count; i++)
                {
                    q_As[i].quiz_id = Convert.ToInt32(generatedId);
                    q_As[i].question_num = i + 1;
                }

                // if there are 5 questions, the following sqlcommand needs to execute 5 times

                foreach (Q_A q_A in q_As)
                {
                    SqlConnection sqlConnection2 = new SqlConnection(connString);

                    using (sqlConnection2)
                    {
                        SqlCommand sqlCommand2 = new SqlCommand();
                        sqlCommand2.CommandText = "INSERT INTO [question_answer] VALUES (@quiz_id, @question_num, @question, @options, @correct_ans)";
                        sqlCommand2.Connection = sqlConnection2;

                        sqlCommand2.Parameters.AddWithValue("@quiz_id", q_A.quiz_id);               // defining the "parameter" used in the sql query
                                                                                                    // setting the value for that parameter (i.e finding "@admin_id" parameter and replacing it the desired value)
                        sqlCommand2.Parameters.AddWithValue("@question_num", q_A.question_num);
                        sqlCommand2.Parameters.AddWithValue("@question", q_A.question);

                        q_A.options_cs = "";

                        for (int i = 0; i < 4; i++)
                            q_A.options_cs += q_A.options_arr[i] + ",";

                        sqlCommand2.Parameters.AddWithValue("@options", q_A.options_cs);
                        sqlCommand2.Parameters.AddWithValue("@correct_ans", q_A.correct_ans);

                        sqlConnection2.Open();
                        sqlCommand2.ExecuteNonQuery();
                        sqlConnection2.Close();
                    }
                }

                return true;
            }
            else
            {
                return false;
            }
        }

        public List<Quiz> GetQuizzesDB(int user_id)    // for when all the quizzes available are to be shown
        {
            List<Quiz> quizzes = new List<Quiz>();

            string connString = ConfigurationManager.ConnectionStrings["DBConnString"].ConnectionString;    // present in Web.config file

            SqlConnection sqlConnection = new SqlConnection(connString);

            using (sqlConnection)
            {
                sqlConnection.Open();

                SqlCommand sqlCommand = new SqlCommand("SELECT * FROM [quiz]", sqlConnection);
                SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();

                while (sqlDataReader.Read())
                {
                    Quiz tempquiz = new Quiz();

                    tempquiz.quiz_id = Convert.ToInt32(sqlDataReader["quiz_id"]);
                    tempquiz.admin_id = Convert.ToInt32(sqlDataReader["admin_id"]);
                    tempquiz.topic_id = Convert.ToInt32(sqlDataReader["topic_id"]);
                    tempquiz.topic_name = GetTopicName(tempquiz.topic_id);
                    tempquiz.title = sqlDataReader["title"].ToString();
                    tempquiz.created_on = Convert.ToDateTime(sqlDataReader["created_on"]);
                    //tempquiz.duration = Convert.ToInt32(sqlDataReader["duration"]);
                    //tempquiz.duration_string = (tempquiz.duration / 60).ToString() + " : " + (tempquiz.duration % 60).ToString();

                    quizzes.Add(tempquiz);
                }

                sqlConnection.Close();
            }

            SqlConnection sqlConnection1 = new SqlConnection(connString);

            using (sqlConnection1)
            {
                for (int i = 0; i < quizzes.Count; i++)
                {
                    sqlConnection1.Open();

                    SqlCommand sqlCommand1 = new SqlCommand("SELECT COUNT(*) FROM [completed_quiz] WHERE [quiz_id]=" + quizzes[i].quiz_id + " AND [user_id]=" + user_id, sqlConnection1);
                    quizzes[i].participated = Convert.ToBoolean(sqlCommand1.ExecuteScalar());

                    sqlConnection1.Close();
                }
            }

            SqlConnection sqlConnection2 = new SqlConnection(connString);

            using (sqlConnection2)
            {
                for (int i = 0; i < quizzes.Count; i++)
                {
                    sqlConnection2.Open();

                    SqlCommand sqlCommand2 = new SqlCommand("SELECT [obtained_mark] FROM [completed_quiz] WHERE [quiz_id]=" + quizzes[i].quiz_id + " AND [user_id]=" + user_id, sqlConnection2);
                    quizzes[i].obtained_mark = Convert.ToInt32(sqlCommand2.ExecuteScalar());

                    sqlConnection2.Close();
                }
            }













            return quizzes;
        }

        public List<Quiz> GetQuizzesAdminDB()    // for when all the quizzes available are to be shown
        {
            List<Quiz> quizzes = new List<Quiz>();

            string connString = ConfigurationManager.ConnectionStrings["DBConnString"].ConnectionString;    // present in Web.config file

            SqlConnection sqlConnection = new SqlConnection(connString);

            using (sqlConnection)
            {
                sqlConnection.Open();

                SqlCommand sqlCommand = new SqlCommand("SELECT * FROM [quiz]", sqlConnection);
                SqlDataReader sqlDataReader = sqlCommand.ExecuteReader();

                while (sqlDataReader.Read())
                {
                    Quiz tempquiz = new Quiz();

                    tempquiz.quiz_id = Convert.ToInt32(sqlDataReader["quiz_id"]);
                    tempquiz.admin_id = Convert.ToInt32(sqlDataReader["admin_id"]);
                    tempquiz.topic_id = Convert.ToInt32(sqlDataReader["topic_id"]);
                    tempquiz.topic_name = GetTopicName(tempquiz.topic_id);
                    tempquiz.title = sqlDataReader["title"].ToString();
                    tempquiz.created_on = Convert.ToDateTime(sqlDataReader["created_on"]);
                    //tempquiz.duration = Convert.ToInt32(sqlDataReader["duration"]);
                    //tempquiz.duration_string = (tempquiz.duration / 60).ToString() + " : " + (tempquiz.duration % 60).ToString();

                    quizzes.Add(tempquiz);
                }

                sqlConnection.Close();
            }

            SqlConnection sqlConnection2 = new SqlConnection(connString);

            using (sqlConnection2)
            {
                for (int i = 0; i < quizzes.Count; i++)
                {
                    sqlConnection2.Open();

                    SqlCommand sqlCommand2 = new SqlCommand("SELECT [Name] FROM [Users] WHERE [UserID]=" + quizzes[i].admin_id + " AND [IsAdmin]= 1", sqlConnection2);
                    quizzes[i].created_by = sqlCommand2.ExecuteScalar().ToString();

                    sqlConnection2.Close();
                }
            }

            return quizzes;
        }

        public static string GetTopicName(int topicID)
        {

SDProject/SDProject/Models/Selection.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace OLS.Models
{
    public class Selection
    {
        [Required(ErrorMessage = "The field cannot be empty")]
        [Display(Name = "Quiz Title:")]
        public string title { set; get; }
        //[Required(ErrorMessage = "The field cannot be empty")]
        //[Display(Name = "Quiz Duration (minutes):")]
        //public int duration { set; get; }
        [Required(ErrorMessage = "The field cannot be empty")]
        [Display(Name = "Quiz Topic:")]
        public int topic_id { set; get; }
        [Required(ErrorMessage = "The field cannot be empty")]
        [Display(Name = "Number of Questions:")]
        public int question_count { set; get; }
    }
}

SDProject/SDProject/Controllers/Q_AController.cs
using OLS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OLS.Controllers
{
    public class Q_AController : Controller
    {
        [HttpGet]
        public ActionResult ParticipateInQuiz(int id)

        {
             
            int user_id = Convert.ToInt32(Session["CurrentUserID"]);    // will take from session later on OR somehow from q_As

            CompletedQuiz completedQuiz = new CompletedQuiz();
            if (completedQuiz.AlreadyParticipated(id, user_id))
                return RedirectToAction("ViewQuiz",new { id = id });
            
            Q_A q_A = new Q_A();
            List<Q_A> q_As = q_A.GetQuizDB(id);

            return View(q_As);
        }

        public ActionResult ViewQuiz(int id)
        {
            int user_id = Convert.ToInt32(Session["CurrentUserID"]);    // will take from session later on OR somehow from q_As

            Q_A q_A = new Q_A();
            List<Q_A> q_As = q_A.GetQuizDB(id,user_id);

            return View(q_As);
        }

        [HttpPost]
        public ActionResult ParticipateInQuiz(List<Q_A> q_As)
        {
            // TODO: 1.Evaluation, 2.mark setting, 3.storing user answers in db
            // if(TryUpdateModel(q_A))

            // 1.Evaluation
            int obtained_mark = 0;
            List<UserAnswers> userAnswers = new List<UserAnswers>();
            for(int i=0;i<q_As.Count;i++)
            {
                // 3.storing user answers in db
                UserAnswers tempUserAnswers = new UserAnswers();

                tempUserAnswers.quiz_id = q_As[i].quiz_id;
                tempUserAnswers.user_id = Convert.ToInt32(Session["CurrentUserID"]); // will take from session later on OR somehow from q_As
                tempUserAnswers.question_num = q_As[i].question_num;
                tempUserAnswers.user_answer = q_As[i].user_answer;

                userAnswers.Add(tempUserAnswers);

                if (q_As[i].correct_ans == q_As[i].user_answer)
                    obtained_mark++;    // put some custom marks later
            }

            // 3.storing user answers in db continued
            UserAnswers userAnswer = new UserAnswers();
            userAnswer.SetUserAnswersDB(userAnswers);

            // 2.mark setting
            CompletedQuiz completedQuiz = new CompletedQuiz();
            completedQuiz.quiz_id = userAnswers[0].quiz_id;
            completedQuiz.user_id = Convert.ToInt32(Session["CurrentUserID"]);  // will take from session later on OR somehow from q_As
            completedQuiz.obtained_mark = obtained_mark;

            completedQuiz.SetCompletedQuizDB(completedQuiz);

            return RedirectToAction("Index","Home",new { id = obtained_mark });
        }
    }
}

SDProject/SDProject/Controllers/QuizController.cs
using OLS.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace OLS.Controllers
{
    public class QuizController : Controller
    {
        [HttpGet]
        public ActionResult Selection()
        {
            if (Session["CurrentUserID"] == null)
            {
                return RedirectToAction("Index", "Home", new { id = "nonexistent" });
            }
            return View();
        }

        [HttpPost]
        public ActionResult Selection(Selection selection)
        {
        
            return RedirectToAction("CreateQuiz", selection);
        }

        [HttpGet]
        public ActionResult CreateQuiz(Selection selection)
        {
            if (selection.question_count == 0)
            {
                return RedirectToAction("Index", "Home", new { id = "nonexistent" });
            }

            Quiz quiz = new Quiz();
            quiz.admin_id = Convert.ToInt32(Session["CurrentUserID"]);

            quiz.title = selection.title;
            //quiz.duration = selection.duration;
            quiz.topic_id = selection.topic_id;
            ViewData["QuestionCount"] = selection.question_count;

            return View(quiz);
        }

        [HttpPost]
        public ActionResult CreateQuiz(Quiz quiz)
        {
            // if (TryUpdateModel<Quiz>(quiz))
            // {
                if (quiz.SetQuizDB(quiz))
                    return RedirectToAction("Index", "Home",new { id = "Success" });
            //ViewData["message"] = "Quiz Created Successfully";
                else
                    return RedirectToAction("Index", "Home", new { id = "Failure" });
            //ViewData["message"] = "Quiz Creation Failed";
            // }


            return RedirectToAction("Index", "Home");
            return View();
        }        

        public ActionResult AllQuizzes()
        {
            if (Session["CurrentUserID"] == null)
            {
                return RedirectToAction("Index", "Home", new { id = "nonexistent" });
            }
            Quiz quiz = new Quiz();
            List<Quiz> quizzes = quiz.GetQuizzesDB(Convert.ToInt32(Session["CurrentUserID"])); // will take from session later on OR somehow from q_As

            return View(quizzes);
        }

        public ActionResult AllQuizzesAdmin()
        {
            if (Session["CurrentUserID"] == null)
            {
                return RedirectToAction("Index", "Home", new { id = "nonexistent" });
            }
            Quiz quiz = new Quiz();
            List<Quiz> quizzes = quiz.GetQuizzesAdminDB();

            return View(quizzes);
        }

        public ActionResult AllParticipatedQuizzes(int id)
        {
            if (Session["CurrentUserID"] == null)
            {
                return RedirectToAction("Index", "Home", new { id = "nonexistent" });
            }
            Quiz quiz = new Quiz();
            List<Quiz> quizzes = quiz.GetQuizzesDB(id);

            return View(quizzes);
        }

        
    }
}

SDProject/SDProject/Views/Quiz/AllQuizzes.cshtml
@model IEnumerable<OLS.Models.Quiz>

@{
    ViewBag.Title = "Quiz List";
}

<body style="background-color:#D3D3D3">
<h1 style="margin-left:40px;margin-top:40px">Quiz List</h1>

<p>
    
</p>
<table class="table" style="margin-top:30px;margin-left:40px">
    <tr>
        <th>
            @Html.DisplayName("Topic")
        </th>
        <th>
            @Html.DisplayName("Title")
        </th>
        <th>
            @Html.DisplayName("Created On")
        </th>
        <th>
            @Html.DisplayName("Participated")
        </th>
        <th>
            @Html.DisplayName("Obtained Mark")
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.topic_name)
        </td>
        <td>
            @Html.ActionLink(@Html.DisplayFor(modelItem => item.title).ToString(), "ParticipateInQuiz", "Q_A", new { id = item.quiz_id }, new { htmlAttributes = new { @class = "form-control" } })  @*TODO: add parameters properly*@
            @*<a href="#">@Html.DisplayFor(modelItem => item.title)</a>*@
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.created_on)
        </td>
        <td>
            @if (Convert.ToBoolean(item.participated) == true)
            {
            <img src="/Images/ok.png"  width="24px" style="margin-left:30px" data-answerid="2003">
            }
            else
            {
            <img src="/Images/notok.png" width="24px"style="margin-left:30px" data-answerid="2003">

            }
        </td>

        <td >
            @Html.DisplayFor(modelItem => item.obtained_mark)
        </td>


    </tr>
}

</table>

    </body>

SDProject/SDProject/Views/Quiz/AllQuizzesAdmin.cshtml
@model IEnumerable<OLS.Models.Quiz>

@{
    ViewBag.Title = "AllQuizzesAdmin";
}

<h1 style="margin-left:40px;margin-top:40px">Quiz List</h1>

    <table  class="table" style="margin-top:30px;margin-left:40px">
        <tr>
            <th>
                @Html.DisplayName("Topic")
            </th>
            <th>
                @Html.DisplayName("Title")
            </th>
            <th>
                @Html.DisplayName("Created On")
            </th>
            <th>
                @Html.DisplayName("Created By")
            </th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.topic_name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.title)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_on)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.created_by)
                </td>
            </tr>
        }

    </table>

SDProject/SDProject/Views/Quiz/CreateQuiz.cshtml
@model OLS.Models.Quiz

@{
    ViewBag.Title = "CreateQuiz";
}



<body style="background-color:#D3D3D3">


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="form-horizontal">
            <div class="mx-auto wrapper login-box " style="width:1000px; background-color:white;background-image: url('../Images/insideBox.jpg')">
                <h4>Create Quiz</h4>
                <hr />
                @Html.ValidationSummary(true, "", new { @class = "text-danger" })
                @*
                    <div class="form-group">
                        @Html.LabelFor(model => model.admin_id, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.admin_id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.admin_id, "", new { @class = "text-danger" })
                        </div>
                    </div>
                *@
                @Html.HiddenFor(model => model.admin_id)
                @Html.HiddenFor(model => model.topic_id)
                @*@Html.HiddenFor(model => model.duration)*@

                @*<div class="form-group">
                        @Html.LabelFor(model => model.topic_id, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.topic_id, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.topic_id, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                <div class="form-group">
                    <h3>@Html.DisplayFor(model => model.title)</h3>
                </div>

                @*<div class="form-group">
                        @Html.LabelFor(model => model.duration, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.duration, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.duration, "", new { @class = "text-danger" })
                        </div>
                    </div>*@

                @for (int i = 0; i < Convert.ToInt32(ViewData["QuestionCount"]); i++)
                {
                    <div class="form-group">
                        @Html.LabelFor(model => model.q_As[i].question, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.q_As[i].question, new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.q_As[i].question, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    @*

                    *@

                    <div class="from-group">
                        @for (int j = 0; j < 4; j++)
                        {
                            <div class="form-group">
                                @Html.LabelFor(model => model.q_As[i].options_arr[j], Convert.ToChar(65 + j) + ". ", htmlAttributes: new { @class = "control-label col-md-2" })
                                <div class="col-md-10">
                                    @Html.EditorFor(model => model.q_As[i].options_arr[j], new { htmlAttributes = new { @class = "form-control" } })
                                    @Html.ValidationMessageFor(model => model.q_As[i].options_arr[j], "", new { @class = "text-danger" })
                                </div>
                            </div>
                        }
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.q_As[i].correct_ans, htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @*@Html.EditorFor(model => model.q_As[i].correct_ans, new { htmlAttributes = new { @class = "form-control" } })
                                @Html.ValidationMessageFor(model => model.q_As[i].correct_ans, "", new { @class = "text-danger" })
                            *@

                            @Html.DropDownListFor(model => model.q_As[i].correct_ans, new List<SelectListItem> { new SelectListItem { Text = "A", Value = "A" }, new SelectListItem { Text = "B", Value = "B" }, new SelectListItem { Text = "C", Value = "C" }, new SelectListItem { Text = "D", Value = "D" } }, "Select Correct Answer", new { htmlAttributes = new { @class = "form-control" } })
                            @Html.ValidationMessageFor(model => model.q_As[i].correct_ans, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <hr />
                }

                <div class="form-group">
                    <div class="col-md-offset-2 col-md-10">
                        <input type="submit" value="Create" class="btn btn-default" />
                    </div>
                </div>
                <h3>@ViewData["Message"]</h3>
            </div>
        </div>
    }

    </body>



    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

SDProject/SDProject/Views/Quiz/Selection.cshtml
@model OLS.Models.Selection

@{
    ViewBag.Title = "Selection";
}





@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<body style="background-image: url('../Images/register6.jpg') ; object-fit:fill;background-repeat: no-repeat;background-size: 2200px 1080px;">

    <div class="form-horizontal">

        <div class="mx-auto wrapper login-box " style="width:1000px; background-color:white;background-image: url('../Images/insideBox.jpg')">

            <h2>Welcome to Quiz</h2>
            <hr />
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.title, new { htmlAttributes = new { @class = "form-control", @required="required" } })
                    @Html.ValidationMessageFor(model => model.title, "", new { @class = "text-danger" })
                </div>
            </div>



            <div class="form-group">
                @Html.LabelFor(model => model.topic_id, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">


                    @Html.DropDownListFor(model => model.topic_id, new List<SelectListItem> { new SelectListItem { Text = "HTML", Value = "1" }, new SelectListItem { Text = "CSS", Value = "2" }, new SelectListItem { Text = "JavaScript", Value = "3" }, new SelectListItem { Text = "Python", Value = "4" }, new SelectListItem { Text = "JAVA", Value = "5" }, new SelectListItem { Text = "C#", Value = "6" } }, "Select Quiz Topic", new { htmlAttributes = new { @class = "control-label", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.topic_id, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.question_count, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.question_count, new { htmlAttributes = new { @class = "form-control", @min = "1", @max = "20", @required = "required" } })
                    @Html.ValidationMessageFor(model => model.question_count, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Next" class="btn btn-default" />

                </div>

            </div>

        </div>

    </div>

    </body>
}